apiVersion: spaces.upbound.io/v1beta1
kind: ControlPlane
metadata:
  name: inventory-prod
  namespace: inventory
  labels:
    acmeco/team: inventory
    acmeco/environment: prod
spec:
  crossplane:
    autoUpgrade:
      channel: Rapid 
  writeConnectionSecretToRef:
    name: inventory-prod
    namespace: inventory