apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-ctp-prod-config
  namespace: argocd
  labels:
    acmeco/team: orders
spec:
  project: default
  source:
    repoURL: https://github.com/cwilhit/xp-at-scale-webinar.git
    targetRevision: HEAD
    path: configuration/orders/orders-prod
    directory:
      recurse: true
  destination:
    name: orders-prod
    namespace: orders