apiVersion: spaces.upbound.io/v1alpha1
kind: SharedBackupSchedule
metadata:
  name: backupschedule-hourly
  namespace: orders
  labels:
    acmeco/team: orders
spec:
  schedule: "@every 1h"
  configRef:
    kind: SharedBackupConfig
    name: default
  controlPlaneSelector:
    labelSelectors:
      - matchExpressions:
          - { key: acmeco/environment, operator: In, values: [prod] }