apiVersion: spaces.upbound.io/v1alpha1
kind: SharedBackupSchedule
metadata:
  name: backupschedule-hourly
  namespace: fulfillment
  labels:
    acmeco/team: fulfillment
spec:
  schedule: "@every 1h"
  configRef:
    kind: SharedBackupConfig
    name: default
  controlPlaneSelector:
    names:
    - fulfillment-prod
