apiVersion: spaces.upbound.io/v1alpha1
kind: SharedSecretStore
metadata:
  name: aws-secretsmanager
  namespace: manufacturing-services
  labels:
    acmeco/team: manufacturing-services
spec:
  controlPlaneSelector:
    labelSelectors:
      - matchExpressions:
          - { key: acmeco/environment, operator: In, values: [prod,test] }
  namespaceSelector:
    names:
      - default
  provider:
    aws:
      service: SecretsManager
      region: us-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-access-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-access-secret
            key: secret-access-key