apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-ctp-prod-config
  namespace: argocd
  labels:
    acmeco/team: fraud
spec:
  project: default
  source:
    repoURL: https://github.com/cwilhit/xp-at-scale-webinar.git
    targetRevision: HEAD
    path: configuration/fraud/fraud-prod
    directory:
      recurse: true
  destination:
    name: fraud-prod
    namespace: fraud