apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-ctp-fraud-prod
  namespace: argocd
  labels:
    acmeco/team: fraud
spec:
  project: default
  source:
    repoURL: https://github.com/upbound/spaces-reference-architecture.git
    targetRevision: HEAD
    path: configuration/fraud/fraud-prod
    directory:
      recurse: true
  destination:
    name: fraud-prod
    namespace: fraud