apiVersion: spaces.upbound.io/v1alpha1
kind: SharedBackupSchedule
metadata:
  name: backupschedule-daily
  namespace: fraud
  labels:
    acmeco/team: fraud
spec:
  schedule: "@every 1d"
  configRef:
    kind: SharedBackupConfig
    name: default
  controlPlaneSelector:
    names:
    - fraud-dev
    - fraud-prod