apiVersion: spaces.upbound.io/v1alpha1
kind: SharedExternalSecret
metadata:
  name: providerconfig-creds-dev
  namespace: fraud
  labels:
    acmeco/team: fraud
    acmeco/environment: dev
spec:
  controlPlaneSelector:
    names:
    - fraud-dev
  namespaceSelector:
    names:
      - default
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      name: providerconfig-creds-dev
    data:
    - secretKey: secret-access-key
      remoteRef:
        key: providerconfig-creds-prod
        version: "v1"