apiVersion: spaces.upbound.io/v1alpha1
kind: SharedBackupSchedule
metadata:
  name: backupschedule-daily
  namespace: marketplace
  labels:
    acmeco/team: marketplace
spec:
  schedule: "@every 1d"
  configRef:
    kind: SharedBackupConfig
    name: default
  controlPlaneSelector:
    names:
    - marketplace-prod
    - marketplace-dev