apiVersion: spaces.upbound.io/v1alpha1
kind: SharedExternalSecret
metadata:
  name: providerconfig-creds-prod
  namespace: marketplace
  labels:
    acmeco/team: marketplace
    acmeco/environment: prod
spec:
  controlPlaneSelector:
    names:
    - marketplace-prod
  namespaceSelector:
    names:
      - default
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      name: providerconfig-creds-prod
    data:
    - secretKey: secret-access-key
      remoteRef:
        key: providerconfig-creds-prod