apiVersion: spaces.upbound.io/v1alpha1
kind: SharedExternalSecret
metadata:
  name: providerconfig-creds-dev
  namespace: marketplace
  labels:
    acmeco/team: marketplace
    acmeco/environment: dev
spec:
  controlPlaneSelector:
    labelSelectors:
      - matchLabels:
          acmeco/environment: dev
  namespaceSelector:
    names:
      - default
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      name: providerconfig-creds-dev
    data:
    - secretKey: secret-access-key
      remoteRef:
        key: providerconfig-creds-prod