apiVersion: spaces.upbound.io/v1alpha1
kind: SharedSecretStore
metadata:
  name: aws-secretsmanager
  namespace: marketplace
  labels:
    acmeco/team: marketplace
spec:
  controlPlaneSelector:
    names:
    - marketplace-prod
    - marketplace-dev
  namespaceSelector:
    names:
      - default
  provider:
    aws:
      service: SecretsManager
      region: us-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-access-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-access-secret
            key: secret-access-key